# slogan: "aeaeae"

# show_heart: true

# show_slogan: true

 menu:
   - title: Archives
     url: archives
     intro: "All the articles."
     icon: "fa fa-archive"
   - title: Categories
     url: categories
     intro: "All the categories."
     icon: "fa fa-folder"
#   - title: Tags
#     url: tags
#     intro: "All the tags."
#     # icon: "fa fa-tags"
#   - title: About
#     url: about
#     intro: "About me."
#     # icon: "fa fa-user"
#   - title: RSS
#     url: atom.xml
#     intro: "Subscribe me."
#     # icon: "fa fa-user"

excerpt:
  depth: 3
  excerpt_excludes: []
  more_excludes: []
  hideWholePostExcerpts: true

# links:
#   - title: hexo-theme-bithack
#     url: https://github.com/Ares-X/hexo-theme-freemind.bithack
#     intro: ""
#     icon: false

#   # - title: "My LinkedIn"
#   #   url: http://www.linkedin.com/in/xxx
#   #   intro: "My Linkin account."
#   #   icon: "fa fa-linkedin"

# widgets:
# - search
# - category
# - tagcloud
# - recent_posts
# - links

# rss: atom.xml
# fancybox: true
# favicon: favicon.png



# # Analytics (change to yours)
# google_analytics:
#   enable: true
#   siteid: UA-70812759-1


# # search
# #swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# #valine comment (change to yours)
# # doc: https://valine.js.org/en/hexo.html
# valine: 
#   enable: false
#   appId: 'xxx'
#   appKey: 'xxx'
#   placeholder: ""
#   visitor: true
#   avatar: 'monsterid'
#   requiredFields: ['nick','mail']
#   pageView: false
  
# #waline comment (change to yours)
# # doc: https://waline.js.org/
# waline:
#   enable: false
#   serverURL: ''
#   pageview: false
#   lang: en
#   dark: true
#   requiredMeta: ['nick', 'mail']
#   locale:
#     placeholder: 'Comment with Email address will get notification when replied'
# # gitalk comment (change to yours)
# # doc: https://github.com/gitalk/gitalk
# gitalk:
#   enable: false
#   clientID: ''
#   clientSecret: ''
#   repo: ''
#   owner: ''
#   admin: ['']
#   id: location.pathname # It is recommended not to change
#   distractionFreeMode: true
    
slogan: "Latest Posts:"

show_heart: false

show_slogan: true

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"


links:
   - title: LinkedIn
     url: http://www.linkedin.com/in/abdomagdy00
     intro: "My Linkin account."
     icon: "fa fa-linkedin"

   - title: Github
     url: https://github.com/vipa0z
     icon: "fa fa-github"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss: atom.xml
fancybox: true
favicon: favicon.jpg
#duoshuo_shortname: 


# Analytics
google_analytics:
  enable: true
  siteid: UA-70812759-1


search:
  enable: true
  swiftype_key: ZP2ZSuHgipSZfRyU8uTR

#valine
valine: 
  enable: false
  appId: 'xxx'
  appKey: 'xxx'
  placeholder: ""
  visitor: false
  avatar: 'monsterid'
  requiredFields: ['nick','mail']
  pageView: false
  
#waline
waline:
  enable: false
  serverURL: ''
  pageview: false
  lang: en
  dark: true
  requiredMeta: ['nick', 'mail']
  locale:
    placeholder: 'Comment with Email address will get notification when replied'

gitalk:
  enable: false
  clientID: ''
  clientSecret: ''
  repo: ''
  owner: ''
  admin: ['']
  id: location.pathname
  distractionFreeMode: true