slogan: "Latest Posts:"

show_heart: true

show_slogan: true

menu:
  - title: Home
    url: index
    intro: "Home"
    icon: "fa fa-home"
  - title: CookBook
    url: cheatsheets/
    intro: "My pentesting notes and CTF Cheatsheets"
    icon: "fa fa-book"
  - title: About Me
    url: about
    intro: "About me."
    icon: "fa fa-user"
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  # - title: Categories
  #   url: categories
  #   intro: "All the categories."
  # icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"

  # - title: Resume
  #   url: about/resume.pdf
  #   intro: "About me."
  #   icon: "fa fa-file"

  # - title: RSS
  #  url: atom.xml
  # intro: "Subscribe me."
  #icon: "fa fa-user"

links:
  - title: Github
    url: https://github.com/vipa0z
    intro: "My Github account."
    icon: "fa fa-github"

  - title: "Linkedin"
    url: http://www.linkedin.com/in/abdomagdy00
    intro: "My LinkedIn account."
    icon: "fa fa-linkedin"
  - title: Email
    url: mailto:AbdelrahmanMagdy.contact@gmail.com
    intro: "My Email address."
    icon: "fa fa-envelope"
  - title: X
    url: https://x.com/vipa0z
    intro: "My X account."
    icon: "fa fa-twitter"
widgets:
  - search
  - category
  - tagcloud
  - recent_posts
  - links

rss: atom.xml
favicon: true
fancybox: true
#duoshuo_shortname:

# Analytics
google_analytics:
  enable: true
  siteid: UA-70812759-1

# search:
#   swiftype_key: ZP2ZSuHgipSZfRyU8uTR

#valine
valine:
  enable: false
  appId: "xxx"
  appKey: "xxx"
  placeholder: ""
  visitor: false
  avatar: "monsterid"
  requiredFields: ["nick", "mail"]
  pageView: false

#waline
waline:
  enable: false
  serverURL: ""
  pageview: false
  lang: en
  dark: true
  requiredMeta: ["nick", "mail"]
  locale:
    placeholder: "Comment with Email address will get notification when replied"

gitalk:
  enable: false
  clientID: ""
  clientSecret: ""
  repo: ""
  owner: ""
  admin: [""]
  id: location.pathname
  distractionFreeMode: true
